version: "3"
services:
  etcd:
    image: bitnami/etcd:3
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - co2e
  server:
    build: .
    ports:
      - "8080:8080"
    env_file: 
      - .env
volumes:
  etcd_data:
    driver: local

networks:
  co2e:
    driver: bridge
